### ISSUE TITLE
npm install --only=production results in many warning

### ISSUE THREAD

**Issue by Coernel82** [jalibu/MMM-NINA#14]
### Platform

magicmirroros

### Node.js Version

10.24.0

### MagicMirror Version

da gibt es weder package.log noch package.json - habe magicmirroros 0.2.0

### Module Version

2ac1be5216f51357ba55909496b07ee09f3e210c

### Description

MMM-NINA lässt sich nicht installieren.
```
pi@magicmirroros:~/magicmirror/mounts/modules/MMM-NINA $ npm install --only=production
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
added 4 packages from 4 contributors in 7.389s
```
Die Fehlermeldung ist auch verwirrend: Ich habe Node.js v10.24.0, und ich soll auf die neueste Version (4, 6, 8 oder 9) upgraden, aber 18 wäre in der Tat schon verfügbar.

### Expected behavior

MMM-NINA installiert sich und zeigt Warnmeldungen an.

### Current behavior

Meldung "Keine Warnungen."

### Steps to reproduce

1. install magicmirroros on Raspberry Pi
2.  sudo apt-get update --allow-releaseinfo-change
3. sudo apt-get update
4. sudo apt-get install docker-compose-plugin
5. cd magicmirror/modules -> git clone https://github.com/jalibu/MMM-NINA.git (bei magicmirroros ist das Verzeichnis magicmirror und nicht MagicMirror)
6. cd MMM-Nina
7. npm install --only=production

Fehlermeldung von oben erscheint.

### config.js

```javascript
{
			module: "MMM-NINA",
			position: "top_right",
			header: "NINA Warnungen",
			config: {
				ags: ["05378024", "05315000", "09373156"], // Liste der Gemeinden, die abgefragt werden sollen
				downgradeLhpSeverity: false,
				downgradeCancelSeverity: true,
				hideCancelledWarnings: false,
				excludeProviders: [], // Mögliche Werte ["MOWAS", "DWD", "BIWAPP", "LHP"] 
				maxAgeInHours: 99999999 ,
				maxWidth: "200px",
				mergeAlertsById: true,
				mergeAlertsByTitle: true,
				showIcon: true,
				showDate: true,
				showCity: true,
				showNoWarning: true,
				theme: "top", // Erlaubte Werte: top, top-floating, side
				updateIntervalInSeconds: 120,
			}
		},
// Die Gemeindeschlüssel sind teils so ausgewählt, dass aktuelle Warnungen vorliegen.
```

### Additional info

Raspberry Pi 3 (ich glaube 3b+ um genau zu sein)

**Comment by jalibu** [comment]
Hi @Coernel82 ,

die NPM Meldungen sind nur Warnungen und nicht zwingend Fehler. Sie haben auch überhaupt nichts mit diesem Modul zu tun ;-)

Wenn du die Meldung "Keine Warnungen" angezeigt bekommst, dann ist das doch ein gutes Zeichen. Oder brennt gerade bei dir in der Nachbarschaft ein Chemiewerk?

**Comment by Coernel82** [comment]
Ich habe spezifisch AGS gesucht, wo es aktuell Warnungen gibt. Auch müsste es konstant Corona Warnungen geben.
Oder funktioniert das Modul so, dass es nur bei neuen Warnungen reagiert und bestehende Warnungen nicht anzeigt, sofern das Modul zum Zeitpunkt der Warnung nicht aktiv war?

**Comment by jalibu** [comment]
Deine AGS sind alle ungültig. Du musst sie exakt so übernehmen wie in [dieser Liste](https://www.xrepository.de/api/xrepository/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:rs_2021-07-31/download/Regionalschl_ssel_2021-07-31.json) (ink. führende Nullen)

**Comment by Coernel82** [comment]
Wow - danke! D.h. bei Wikipedia und Co. sind die alle unvollständig!

**Comment by jalibu** [comment]
keine ahnung. in der anleitung zu diesem modul verweise ich auch auf exakt diese liste und nicht auf wikipedia

**Comment by jalibu** [comment]
case closed
