### ISSUE TITLE
Corona-Warnmeldungen ausblenden

### ISSUE THREAD

**Issue by Coernel82** [jalibu/MMM-NINA#15]
Danke für die Hilfe neulich, das Hauptproblem lag vermutlich am MagicMirrorOS - eine "normale" Installation war perfekt, deine App ist toll.

Wie sieht es aus, besteht die Möglichkeit die ganzen Corona-Warnmeldungen auszublenden? Im Prinzip sowas:

```java
if ($stringContains == *corona*) {
	showWarning = false;
}
```

**Comment by Padd37** [comment]
Super einfach und schnell installiert. Danke für deine tolle Arbeit!

**Comment by jalibu** [comment]
Hat sich erledigt, oder? :-)
