### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by MajorC1983** [jalibu/MMM-NINA#17]
### MagicMirror Version

2.24.0

### Module Version

last version

### Description

Moin,

ich bekomme in meinem MM folgenden Fehler.

`0|MagicMirror  | [24.09.2023 16:52.17.187] [WARN]  API request for 110030003003 failed: invalid json response body at https://warnung.bund.de/api31/dashboard/110030000000.json reason: Unexpected end of JSON input`

Ich bin aber der Meinung, dass 110030003003 die richtige Nummer für Berlin-Pankow ist.

In der Config schaut es so aus:

`ags: ["110030003003", "110000000000"],`

Irgend eine Idee, was es sein könnte?

### Steps to reproduce

Start MM

pm2 logs --lines=50

### Log

```shell
0|MagicMirror  | [24.09.2023 16:52.17.187] [WARN]  API request for 110030003003 failed: invalid json response body at https://warnung.bund.de/api31/dashboard/110030000000.json reason: Unexpected end of JSON input
```

### config.js

```javascript
{
			module: "MMM-NINA",
			position: "top_right",
			//header: "NINA",
			config: {
				updateIntervalInSeconds: 320,
				maxAgeInHours: 36,
				hideCancelledWarnings: true,
				mergeAlertsByTitle: true,
				showNoWarning: false,
				showIcon: true,
				showDate: true,
				showCity: true,
				theme: "side",
				ags: ["110030003003", "110000000000"], //Berlin-Pankow
			}
		},
```

**Comment by jalibu** [comment]
Gemäß https://nina.api.bund.dev/ stellt die Schnittstelle von NINA keine genaueren Daten zur Verfügung, sondern aggregiert auf Kreisebene. 
<img width="1424" alt="image" src="https://github.com/jalibu/MMM-NINA/assets/25933231/f55e2702-eb07-4cb0-9ed2-1621eebb78ce">

**Comment by MajorC1983** [comment]
Vielen Dank,

mit nur Berlin klappt es.
