### ISSUE TITLE
Entwarnungen am Ende der Liste anzeigen

### ISSUE THREAD

**Issue by drtorchwood** [jalibu/MMM-NINA#18]
**Is your feature request related to a problem? Please describe.**
Wenn viele Nachrichten eintreffen, sind die Nachrichten nicht nach Wichtigkeit geordnet. Dies trifft zum Beispiel auf, wenn eine Wetterwarnung aufgehoben und durch eine neue ersetzt wird. Da ich die Warnungen unter ein paar anderen Modulen am rechten Rand anzeige, kann es dann passieren, dass eine wichtige nicht mehr auf den Bildschirm passt. 
Hab's schon mit `downgradeCancelSeverity` probiert, aber das hat keinen Effekt. 

**Describe the solution you'd like**
Es wäre gut, wenn Warnungen nach Wichtigkeit sortiert wären und Entwarnungen ganz am Ende der Liste erscheinen.

**Comment by jalibu** [comment]
Hi @drtorchwood ,

danke für deinen Input zur Verbesserung dieses Moduls.

Bitteschön: https://github.com/jalibu/MMM-NINA/releases/tag/v1.8.0

**Comment by drtorchwood** [comment]
Das ging fix. Vielen Dank!
