### ISSUE TITLE
[ENHANCEMENTS] Proposals for the UI

### ISSUE THREAD

**Issue by fnsign** [jalibu/MMM-NINA#2]
- Wenn keine Warnungen anliegen, sollte lediglich “Keine Warnungen” als Nachricht erscheinen in #666 statt grün und ohne Haken davor. Das würde besser zu MMM-DWDWarweather Modul passen ☺.

- In der config würde ich noch das `header:` property angeben, das man sich nach Wunsch umbenennen kann. Ausserdem hat man dann auch eine schöne Headline über dem Modul.

**Comment by jalibu** [comment]
Hi @fnsign 

habe die Änderung gemacht.

Bzgl Header: Das ist eine MM default Funktion.
```
{
			module: "MMM-NINA",
			position: "top_right",
			header: "Jan ist toll. Ich werde ihm spenden.",
			config: {}
}
```
