### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Unisol2003** [jalibu/MMM-NINA#20]
Hi,
ich heiße Michael und bin ganz neu hier. Habe das NINA Modul auf meinem MM. Nun soll ich ein Update machen. Wo bekomme ich das her oder wie mache ich das? Ich suche schon seit Tagen nach antworten. LG Michael

**Comment by jalibu** [comment]
Hi Michael,

vermutlich hast du das Modul (wie alle anderen Module auch) über ein `git clone` auf dein System geladen.

Um deinen lokalen Stand auf die neuste Version zu bringen, verwendest du am besten folgenden Befehl  
`git fetch && git pull`

**Comment by KristjanESPERANTO** [comment]
Hast du Änderungen an dem Modul durchgeführt? Was sagt denn `git status`? Das sollte zeigen welche Dateien geändert wurden.

**Comment by jalibu** [comment]
mach erst ein 'git checkout package-lock.json‘ und dann den pull

**Comment by jalibu** [comment]
@Unisol2003 das Problem sollte nun für immer und ewig behoben sein ;-)
