### ISSUE TITLE
Horizontal srcollender Text bei Warnungen

### ISSUE THREAD

**Issue by fnsign** [jalibu/MMM-NINA#5]
**Is your feature request related to a problem? Please describe.**
Ich habe das Modul auf dem MM  in der rechten Spalten mit einer Breite von 300px stehen. Manchmal kommen Warnmeldungen rein die, teilweise 2/3 der Spiegelbreite einnehmen und alle Module auf der Seite komplett verschieben. 

**Describe the solution you'd like**
Um dies zu vermeinden, sollten die Warntexte über die Breite von 300px als infinite loop von rechts nach links scrollen. Wenn keine Warnungen anliegen, dann bleibt der Standardtext stehen.  

Evtl. kann die Breite des Moduls auch als property angegeben werden, falls  es  mehr als 300px breit ist, weil es z.B. in bottom_middle eingebettet ist.

**Comment by jalibu** [comment]
Hi @fnsign ,
wie wäre es einfach mit nem Line Break?

**Comment by jalibu** [comment]
Scrollen ist meiner Meinung nach immer problematisch. Sowohl aus User Experience Sicht, aber auch für den Entwickler :-D

**Comment by fnsign** [comment]
Hi Jan,
ich habe auch bereits mit marquee effects in CSS rumprobiert, aber bekomme es leider nicht nicht hin. 
Ein LB wäre schon mal eine recht praktikable Lösung, um das Problem mit den verschobenen Module zu vermeiden.

**Comment by jalibu** [comment]
man kann jetzt eine maximale breite angeben

**Comment by jalibu** [comment]
Von der Optik bin ich nicht zufrieden mit diesem Modul. Ich bin allerdings auch ein sehr schlechter Designer. Falls hier jemand mehr Talent hat als ich, darf er oder sie mir gerne mal ein paar Mockups schicken.

**Comment by fnsign** [comment]
Besten Dank! Ich warte mal auf di nächste Warnung und bin gespannt, wie es aussieht.

**Comment by fnsign** [comment]
Die eingefügten Line Breaks schaun gut aus! Ich schliesse den issue und sage noch mal besten Dank!
